### PR TITLE
Updates dependencies and fixes tests for phpunit update

### LINKED ISSUE #62: Support for symfony 4.2
1. Tests pass with symfony/yaml 3.4.* and tightenco/collect 5.6.* and they don't have any dependency conflicts with symfony 4.2.*

2. tightenco/collect 5.5.33 can't work with symfony 4.2.* due to locked dependecy symfony/var-dumper: ~3.3

3. But tightenco/collect 5.6.* only supports php 7.1.3+ (as well as symfony 4.2)

4. Symfony 4.2 also requires the symfony/yaml to be at 'self' version (as in 4.2). When upgrading symfony/yaml to 4.2 I noticed some unit tests failing (related to space after comma , not sure if a big deal or not)

_Originally posted by @kezek in https://github.com/okta/okta-sdk-php/pull/61#issuecomment-451420674_

### LINKED ISSUE #63: tightenco/collect namespace conflicts.
Im unable to install this package through composer due to namespace conflicts with your "tightenco/collect": "5.5.33" package and Laravel >= 5.6.*.

I believe newer versions of Collect have corrected this issue though.

### LINKED ISSUE #64: Update nesbot/carbon version
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.

### PR DESCRIPTION
**Pull request by bretterer**
** Updates
 - Updates travis.yaml to test only php 7.2 - php 7.3
 - Updates required version of to be php 7.2
 - Updates package tightenco/collect to v5.8.31 ( Resolves #63 )
 - Updates package phpunit/phpunit to ^8.0
 - Updates symfony/yaml to ^4.3 (Resolves #62 )
 - Updates symfony/var-dumper to ^4.3 (Resolves #62 )
 - Updates nesbot/carbon to ^2.0 ( Resolves #64 )

** Changes
 - Modifies all tests for `setUp` `setUpBeforeClass` `tearDownAfterClass` to have return type of `void` to fix errors after updating phpunit
 - Modifies `operatorForWhere` to have a default operator of `null` in the collect object as required from update to tightenco/collect
 - changes tests to use assertStringContainsStringIgnoreCase due to update of phpunit and deprecated methods
 - some whitespace changes for cleanup

### CODE REVIEW

File: src/Resource/AbstractCollection.php [hunk 1]
```diff
@@ -30,7 +30,7 @@ class AbstractCollection extends Collection
      * @param  mixed  $value
      * @return \Closure
      */
-    protected function operatorForWhere($key, $operator, $value = null)
+    protected function operatorForWhere($key, $operator = null, $value = null)
     {
         if (func_num_args() == 2) {
```
Comment (laura-rodriguez) [inline src/Resource/AbstractCollection.php]: now that the default value for `$operator = null`, is this logic still up to date? I guess it is since tests are passing, just a sanity check.

Comment (bretterer) [reply src/Resource/AbstractCollection.php]: Yup.  This method over-rides the one that comes from the package, so the signatures have to match.   they added `= null` which means I have to in this method.
